In [1]:
import pandas as pd
from splinter import Browser
from bs4 import BeautifulSoup
from webdriver_manager.chrome import ChromeDriverManager
import time

## Athlete Name and UFC Page

In [2]:
# Read CSV with data
df = pd.read_csv('../csv/combined_fighter.csv')

In [3]:
# Isolate athlete names
# Drop duplicates
athletes_df = pd.DataFrame(df["fighter"].drop_duplicates())
athletes_df

                  fighter
0            Adrian Yanez
1            Trevin Giles
2             Tai Tuivasa
3           Cheyanne Buys
4           Marion Reneau
...                   ...
12019  Alberta Cerra Leon
12020    Robert Lucarelli
12021       David Levicki
12022          Ray Wizard
12023      Sean Daugherty

[2139 rows x 1 columns]

In [4]:
# Split fighter name to first and last name

splitted = athletes_df['fighter'].str.split()
athletes_df['first_name'] = splitted.str[0]
athletes_df['last_name'] = splitted.str[-1]
middle = splitted.str[1] 
athletes_df['middle_name'] = middle.mask(middle == athletes_df['last_name'], '')
athletes_df['webpage'] = "https://www.ufc.com/athlete/" + athletes_df['first_name'] + "-" + athletes_df['last_name']

athletes_df

,fighter,first_name,last_name,middle_name,webpage
0,Adrian Yanez,Adrian,Yanez,,https://www.ufc.com/athlete/Adrian-Yanez
1,Trevin Giles,Trevin,Giles,,https://www.ufc.com/athlete/Trevin-Giles
2,Tai Tuivasa,Tai,Tuivasa,,https://www.ufc.com/athlete/Tai-Tuivasa
3,Cheyanne Buys,Cheyanne,Buys,,https://www.ufc.com/athlete/Cheyanne-Buys
4,Marion Reneau,Marion,Reneau,,https://www.ufc.com/athlete/Marion-Reneau
...,...,...,...,...,...
12019,Alberta Cerra Leon,Alberta,Leon,Cerra,https://www.ufc.com/athlete/Alberta-Leon
12020,Robert Lucarelli,Robert,Lucarelli,,https://www.ufc.com/athlete/Robert-Lucarelli
12021,David Levicki,David,Levicki,,https://www.ufc.com/athlete/David-Levicki
12022,Ray Wizard,Ray,Wizard,,https://www.ufc.com/athlete/Ray-Wizard
12023,Sean Daugherty,Sean,Daugherty,,https://www.ufc.com/athlete/Sean-Daugherty

In [10]:
#FIX MIDDLE NAME ISSUE
#COUNT HOW MANY VALUES HAVE A MIDDLE NAME (either manually fix

# middlename = athletes_df['middle_name'] != ""
# middlename

import numpy as np

athletes_df['middle_name'].replace('', np.nan, inplace = True)
# athletes_df

athletes_df.dropna(subset = ['middle_name'], inplace = True)
athletes_df.to_csv('athletes_df.csv')

In [ ]:
# UPDATE THE LIST ABOVE

## Data Scraping: Bio Image

In [ ]:
# Setup splinter
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

In [ ]:
# Scrape the UFC Athlestes Site
img_url = "https://www.ufc.com/athlete/adrian-yanez"
browser.visit(img_url)

In [ ]:
# Create html and tie to BeautifulSoup
html = browser.html
soup = BeautifulSoup(html, "html.parser")

In [ ]:
# View site HTML
print(soup.prettify())

In [ ]:
# athlete_img = soup.find("img")
# athlete_img2 = athlete_img["src"]
# athlete_img2

img = soup.find("div", class_ = "c-bio__image").find("img")["src"]

# img = soup.find("div", class_ = "downloads").find("ul").find("li").find("a")["href"]
#featured_img = ("https://marshemispheres.com/" + featured_img)
img



# featured_img = img_soup.find("img", class_ = "fancybox-image")

# featured_img_url =featured_img["src"]
# featured_img_url = ("https://spaceimages-mars.com/" + featured_img_url)
# featured_img_url

# http_athlete_href = []

# # Get all href links
# for link in soup.find_all('a'):
#     # link.
#     print(link.get('href'))

In [ ]:
img_mobile = soup.find("div", class_ = "c-bio__image--mobile").find("img")["src"]
img_mobile

In [ ]:
athlete_web = athletes_df['webpage'][1]
athlete_web

# athlete = len(athletes_df['webpage'])
# athlete

In [ ]:
#athlete = len(athletes_df['webpage'])

for athlete in len(athletes_df['webpage']):
    
    # Scrape the UFC Athlestes Site
    img_url = athletes_df['webpage'][0] #should be x / athlete
    browser.visit(img_url)
    
    # Create html and tie to BeautifulSoup
    html = browser.html
    soup = BeautifulSoup(html, "html.parser")
    
    #
    img = soup.find("div", class_ = "c-bio__image").find("img")["src"]
    athlete_df['bio_image']

In [ ]:
browser.quit()